In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from mlxtend.plotting import plot_decision_regions
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import numpy as np

# Generating sample data
np.random.seed(42)  # For reproducibility

# CGPA ranges from 6.0 to 10.0
cgpa = np.round(np.random.uniform(6.0, 10.0, 100), 2)

# Package ranges from 5.0 to 15.0, increasing with CGPA
package = 5.0 + (cgpa - 6.0) * (15.0 - 5.0) / (10.0 - 6.0)
# Adding some noise to the package
package += np.random.normal(0, 0.5, 100)
package = np.round(package, 2)

# Creating a DataFrame
data = {
    'cgpa': cgpa,
    'pac': package
}

dataset = pd.DataFrame(data)

In [3]:
x = dataset.iloc[:,:-1]
y = dataset["pac"]

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
from sklearn.model_selection import cross_val_score

In [20]:
from sklearn.model_selection import LeaveOneOut,LeavePOut,KFold,StratifiedKFold

In [21]:
# r = cross_val_score(LinearRegression(),x,y,cv=5)
r = cross_val_score(LinearRegression(),x,y,cv=KFold(n_splits=10))

In [22]:
r.sort()
r*100

array([94.20793514, 95.97935975, 96.39816884, 97.36740801, 97.47983517,
       97.81456771, 98.13869066, 98.32642925, 98.38348285, 98.70305793])

In [4]:
new_data = dataset.head(10)

In [5]:
x_new = new_data.iloc[:,:-1]
y_new = new_data["pac"]

In [6]:
from sklearn.model_selection import LeaveOneOut,LeavePOut,KFold,StratifiedKFold

In [7]:
lo = LeaveOneOut()
for train , test in lo.split(x_new,y_new):
    print(train,test)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [10]:
lo1 = LeavePOut(p=2)
for train , test in lo1.split(x_new,y_new):
    # print(train,test)

SyntaxError: incomplete input (2568714157.py, line 3)

In [11]:
kf = KFold(n_splits=5)
for train , test in kf.split(x_new,y_new):
    print(train,test)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]
